### ISSUE TITLE
If any translation has the wrong format, then all translations in the app break.

### ISSUE THREAD

**Issue by COSTADOR** [lephyrus/ngx-translate-messageformat-compiler#102]
"@angular/core": "^15.0.0",
"@ngx-translate/core": "^14.0.0",
"ngx-translate-messageformat-compiler": "^6.2.0",

If any translation has the wrong format, then all translations in the app break.

Example: [stackblitz.com](https://stackblitz.com/edit/ngx-translate-messageformat-compiler-example-4z9bzg)
For example instead of using =0{ we have 0{

Maybe it is possible to return the wrong key instead all translations do crash due to one error?

**Comment by jaideepsingh** [comment]
@lephyrus Thank you very much for merging the PR and the new release. I guess we can close this issue now.

**Comment by lephyrus** [comment]
Closed by #115.
