### ISSUE TITLE
Support Angular 5

### ISSUE THREAD

**Issue by Nxt3** [lephyrus/ngx-translate-messageformat-compiler#13]
This seems to do nothing in my Angular 5 app. I copied and pasted exactly what you had in your examples and nothing worked.

**Comment by lephyrus** [comment]
Angular 5 is supported and works for me. To make this report helpful, you're going to have to be much more specific as to what you did and what problem you encountered.

**Comment by lephyrus** [comment]
Closing. Please reopen with more details if necessary.
