### ISSUE TITLE
Can't mix pluralization and variable replacement in JSON

### ISSUE THREAD

**Issue by krysalead** [lephyrus/ngx-translate-messageformat-compiler#15]
Hi,

Thanks for your implementation. 
I got an issue today mixing pluralization syntax and replacement syntax in json file. I got a parsing issue. If I remove the ngx-translate-messageformat-compiler from the module config I can use the variable replacement but no more the pluralization.

JSON
-------
{
"home": {
    "title": "Hello {{userName}}",
    "label": {
      "weeks": "{nbWeek, plural, one{week} other{# weeks}}"
    }
  }
}

Ngmodule
------

 TranslateModule.forRoot({
      loader: {
        provide: TranslateLoader,
        useFactory: HttpLoaderFactory,
        deps: [HttpClient]
      },
      compiler: {
        provide: TranslateCompiler,
        useClass: TranslateMessageFormatCompiler
      }
    })

Thanks & regards

Olivier

**Comment by lephyrus** [comment]
You need to use messageformat's syntax, which does not use double curly braces. Please read the REAMDE.

**Comment by krysalead** [comment]
Sorry, I missed it.
