### ISSUE TITLE
Compiler doesn't work correctly

### ISSUE THREAD

**Issue by alonstar** [lephyrus/ngx-translate-messageformat-compiler#27]
I'm using Angular 6.0.4 + ngx-translate/core 10.0.2 + messageformat 2.0.2 + ngx-translate-messageformat-compiler 4.1.3.

Two language : en-US, zh-HK (en-US is default)
My website can't show message correctly, so I tried to find out what's wrong in my project.
I added log in the function

    TranslateMessageFormatCompiler.prototype.compileTranslations = function (translations, lang) {		
		log("COMPILE before (" + lang + ")");	
		var result = this.messageFormat.compile(translations, lang);		
		log("COMPILE after (" + lang + ")", result);	
        return result;
    };

Then I found the en-US didn't return. I don't know why lang is undefined and where it comes from.

	[TranslateMessageFormatCompiler] COMPILE before (en-US)
	[TranslateMessageFormatCompiler] COMPILE before (undefined)
	[TranslateMessageFormatCompiler] COMPILE after (undefined) {Loading: ƒ, Language: ƒ, Menu: {…}, Field: {…}, Button: {…}, …}

So I removed the lang parameter from messageFormat.compile function.

    TranslateMessageFormatCompiler.prototype.compileTranslations = function (translations, lang) {		
		log("COMPILE before (" + lang + ")");	
		var result = this.messageFormat.compile(translations);		
		log("COMPILE after (" + lang + ")", result);	
        return result;
    };

And it works correctly.

	[TranslateMessageFormatCompiler] COMPILE before (en-US)
	[TranslateMessageFormatCompiler] COMPILE after (en-US) {Loading: ƒ, Language: ƒ, Menu: {…}, Field: {…}, Button: {…}, …}

Or add langs when new MessageFormat(['en-US', 'zh-HK']), it also works.

It looks like messageformat can't mapping the lang so it doesn't work. How could I do to resolve my problem? 

Thanks.

**Comment by lephyrus** [comment]
Fixed by #29.
