### ISSUE TITLE
Can't use translate/[translate] directive

### ISSUE THREAD

**Issue by johnfrades** [lephyrus/ngx-translate-messageformat-compiler#28]
Hi, i just want to ask, i'm trying to use translate/[translate] directive but it seems it doesn't work on your library
Here's the example:

Not working:
`<span translate="AREAS" [translateParams]="{ count: 3 }">areas</span>`
`<span [translate]="'AREAS'" [translateParams]="{ count: 3 }">areas</span>`
The error says `"Count is undefined"`

Working:
`<span translate [translateParams]="{ count: 3 }">AREAS</span>`

Just want to know on how to make it work with the 2 Not Working examples.

**Comment by lephyrus** [comment]
That's not enough information. Can you do a minimal reproduction on StackBlitz please?

**Comment by artuska** [comment]
Added `TranslateMessageFormatDebugCompiler` to see debug in console and it shows:

```
[TranslateMessageFormatCompiler] INTERPOLATE Step {current} of {total} undefined
```

**Comment by artuska** [comment]
This does not work even in latest versions of translate plugins.

Angular — 7.2.5
Translate — 11.0.1
Translate Messageformat Compiler — 4.4.0
