### ISSUE TITLE
addFormating

### ISSUE THREAD

**Issue by YunnXairou** [lephyrus/ngx-translate-messageformat-compiler#31]
Can someone please let us use to function addFormatters with this compiler?
Because messageFormat is private, so I don't see how I can add my custom formatters for my entire app and not just one module.

**Comment by lephyrus** [comment]
I should be able to expose this the same way the "biDiSupport" and "strictNumberSign" configuration options are already. Seems more useful than those, actually. 👍 I'll try and add this soon.
