### ISSUE TITLE
Is it possible to pass a custom default currency to the compiler?

### ISSUE THREAD

**Issue by PhilippCh** [lephyrus/ngx-translate-messageformat-compiler#33]
Hi there!

we'd like to specify a different default language when using this library. According to https://messageformat.github.io/messageformat/page-guide this is possible using `mf.currency = 'EUR'` before the first call to `compile()`.

Since a new `MessageFormat` instance is created as a private member in `TranslateMessageFormatCompiler`, there is currently no way to specify this, right?

If there's no quick fix for it; I'd be willing to create a PR.

Cheers
Philipp

**Comment by lephyrus** [comment]
Strange, this seems to be missing from the [API documentation](https://messageformat.github.io/messageformat/MessageFormat). Anyway, this should be fairly straight-forward to add in the same way you can already pass `formatters`, `locales` and more via `MESSAGE_FORMAT_CONFIG`. I'll be happy to look at your PR if you have a go!
