### ISSUE TITLE
Dynamic variable in html template 

### ISSUE THREAD

**Issue by KevinJue** [lephyrus/ngx-translate-messageformat-compiler#37]
Hello, 

I'm actually trying to use pluralization, it work fine like that: 

```
{{'STORE.STOREFOUND' | translate:"{ count: 2 }"}}
"STOREFOUND": "We found {count, plural, =0{nothing} one{# store} other{# stores}}."
```
output look like it should be.

But i'm trying to use a dynamic value for the count
`{{'STORE.STOREFOUND' | translate:"{ count: {{numberOfStores}} }"}}`

@lephyrus is it possible, because i found any solution on your readme ?

**Comment by lemoinem** [comment]
@KevinJue You could also omit the quote around your count object:
`{{'STORE.STOREFOUND' | translate:{ count: numberOfStores } }}`

**Comment by byzg** [comment]
Pay attention for the last space in @lemoinem message
https://github.com/angular/angular/issues/9571
