### ISSUE TITLE
Peer Dependency of messageformat seems to be wrong

### ISSUE THREAD

**Issue by penghuili** [lephyrus/ngx-translate-messageformat-compiler#41]
The peerDependencies of messageformat:
```
"messageformat": ">=2.0.0 <=2.0.2 || >2.0.4 <3.0.0"
```
But the current lastest version of messageformat is 2.0.4, so shouldn't it be:
```
"messageformat": ">=2.0.0 <=2.0.2 || >=2.0.4 <3.0.0"
```
?

**Comment by vtolstov** [comment]
gentle ping...

**Comment by lephyrus** [comment]
Actually, I was right the first time. Both 2.0.3 and 2.0.4 were a problem for us because of this: https://github.com/messageformat/messageformat/pull/210
