### ISSUE TITLE
Translates not working at all

### ISSUE THREAD

**Issue by mcpierce** [lephyrus/ngx-translate-messageformat-compiler#45]
I followed the instructions for adding the dependency and updating my translates, but the entire translation system stopped working once those steps were followed; i.e., now **NO** translations work. Only the untranslated keys are displayed across the entire application.

The changes to my application to use ngx-translate-messageformat-compiler are as follows:

### package.json
```
    "@ngx-translate/core": "^11.0.1",
    "@ngx-translate/http-loader": "^4.0.0",
    "ngx-translate-messageformat-compiler": "^4.4.0",
```

### app.module.ts
```
    TranslateModule.forRoot({
      compiler: {
        provide: TranslateCompiler,
        useClass: TranslateMessageFormatCompiler
      },
      loader: {
        provide: TranslateLoader,
        useFactory: HttpLoaderFactory,
        deps: [HttpClient]
      }
    }),
```

### en.json
```
"call-interval-schedule-page": {
  "table": {
    "row:" {
      "contact-action-label": "{position, selectordinal, one{#st} two{#nd} few{#rd} other{#th}} Contact"
    }
  }
}
```

### page.html
```
<tr *ngFor='let action of contact_actions; let i = index'>
        <td>{{'call-interval-schedule-page.table.row.contact-action-label'|translate:{position:i} }}</td>
</tr>
```

### The Generated Output
```
call-interval-schedule-page.table.row.contact-action-label
```

**Comment by mcpierce** [comment]
Sorry, that was an error in copying over the text from my translation file (didn't want to bring the full 288 lines). The key in the HTML and what's in the translation file do in fact match.

**Comment by lephyrus** [comment]
Hi @mcpierce! This is not a support forum, I'm afraid. It's unlikely that the library is fundamentally broken for everyone, so your issue does not qualify as a bug report.

I generally like to help, as do others. But you need to do your part. Make it as easy as possible for us. Find the source of the error. Look at the logs. Do some debugging. Try ngx-translate without this plugin. Make a minimal reproduction on StackBlitz.

Good luck!

**Comment by mcpierce** [comment]
I think I'll instead find another project and work with them rather than use one from someone so dismissive.

**Comment by lephyrus** [comment]
I guess I was more dismissive than necessary, sorry. But my point stands. At the very least, put your example on StackBlitz. You can even fork my example (top of README).

**Comment by mcpierce** [comment]
Thank you for realizing that.

I've [forked](https://stackblitz.com/edit/ngx-translate-messageformat-compiler-failure) the example app to create a minimal example that demonstrates the issue I'm experiencing.

In doing so, I believe I've nailed down the problem. I had already been using ngx-translate and had values being interpolated with {{value}}, for example. When I added ngx-translate-messageformat-compiler to the mix, these entries caused all of the translations to stop working. Changing them to {value} fixed the issue.

Perhaps adding a note in the README file to let someone migrating over to use this project that they need to fix any such translation entries would be in order?

**Comment by lephyrus** [comment]
It's there actually, under "Usage" (search for "single curly braces"), but clearly not visible enough - not the first time that's been the problem. The README has grown over time (bigger than the actual runtime code for sure!). I guess it need an overhaul...

Glad it's working for you now.

**Comment by jonjaques** [comment]
@lephyrus I experienced this behavior recently where one bad value (incorrect syntax) for one key breaks all translated values. Seems to me that is not desired behavior under any circumstances and this should be a bug.

**Comment by PulseVT** [comment]
@jonjaques If you have MESSAGE_FORMAT_CONFIG provided, try to add multi: true to that provider. That's what helped me in a similar case.

**Comment by PulseVT** [comment]
@jonjaques 
Probably I had similar issue - everything was configured fine, but translations didnt render. If you are providing MESSAGE_FORMAT_CONFIG, try specifying **multi: true** for that provider - it was last issue preventing translations from working in my case.

**Comment by vdiaz1130** [comment]
> It's there actually, under "Usage" (search for "single curly braces"), but clearly not visible enough - not the first time that's been the problem. The README has grown over time (bigger than the actual runtime code for sure!). I guess it need an overhaul...
> 
> Glad it's working for you now.

Is there a solution other than converting double brace to single? We started using MessageFormat after the implementation of ngx-translate. We have almost 4,000 references of the double brace {{}}.
