### ISSUE TITLE
Spaces in selector icu

### ISSUE THREAD

**Issue by Noppey** [lephyrus/ngx-translate-messageformat-compiler#60]
Hi,

I'm using ICU messageformat.js
How is it possible to use a selector for multiple words. I'll given an example.
'EXAMPLE': '{value, select, FirstValue{ok} SecondValue{alsoOk} Third Value{exception due to space}}'

I want "Third Value" to be a valid option to depend my sentence on.

**Comment by lephyrus** [comment]
This does not relate to this library, but to [ICU syntax](https://messageformat.github.io/messageformat/page-guide). I hope you've figured it out in the meantime.
