### ISSUE TITLE
Class constructor TranslateCompiler cannot be invoked without 'new'

### ISSUE THREAD

**Issue by lucasskluser** [lephyrus/ngx-translate-messageformat-compiler#66]
Hi from Brazil!

I'm trying to use TranslateMessageFormatCompiler in an Angular 7.1 project, however, my application doesn't work, as the following error is thrown:

![image](https://user-images.githubusercontent.com/28795323/88980104-58ced280-d299-11ea-8106-c6370400a780.png)

Angular CLI: 7.3.10
Node: 13.12.0
OS: win32 x64
Angular: 7.1.4
@ngx-translate/core: 13.0.0
ngx-translate-messageformat-compiler: 4.7.0
messageformat: 2.0.5

In my app.module imports:

![image](https://user-images.githubusercontent.com/28795323/88980196-8fa4e880-d299-11ea-8c1f-e15a99415e10.png)

And providers:

![image](https://user-images.githubusercontent.com/28795323/88980260-acd9b700-d299-11ea-9c21-d1cd53a4f8f7.png)

I appreciate if you can help me.

**Comment by jessorlisa** [comment]
Having the same issue with Angular 10:

```
Angular CLI: 10.1.2
Node: 12.18.3
OS: darwin x64

Angular: 10.1.2
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1001.2
@angular-devkit/build-angular   0.1001.2
@angular-devkit/core            10.1.2
@angular-devkit/schematics      10.1.2
@angular/cdk                    10.2.1
@angular/material               10.2.1
@schematics/angular             10.1.2
@schematics/update              0.1001.2
rxjs                            6.6.3
typescript                      3.9.7

```

Is there anything we should provide to narrow this down?

**Comment by jessorlisa** [comment]
@lucasskluser Did you find a solution?

**Comment by lephyrus** [comment]
A quick internet search tells me that this probably has to do with module formats and/or what language level is targeted by the library and/or the app including it. I know that's vague, but the thing is: this library provides all kinds of builds (using the standard Angular CLI setup for libraries) and this error does not occur with a default Angular CLI setup for the app using it.

I suggest you try to find the difference between your app setup and the [sample projects](https://github.com/lephyrus/messageformat-compiler-test-projects) or the [StackBlitz app](https://stackblitz.com/edit/ngx-translate-messageformat-compiler-example). Check `tsconfig.js` (there's usually more than one), `angular.json` and `package.json` especially.

**Comment by vincentpalita** [comment]
@jessorlisa / @lucasskluser Do you have a specific webpack config? The default one from angular should just work fine. I had the same issue using this module in Storybook. I found a way to fix this, thanks to this issue: https://github.com/storybookjs/storybook/issues/11379#issuecomment-662953505

This configuration is done by angular-cli in the hidden webpack config.

**Comment by lephyrus** [comment]
Closed for staleness. Feel free to re-open if you encounter this.
