### ISSUE TITLE
Add support for Angular 11

### ISSUE THREAD

**Issue by marcobuschini** [lephyrus/ngx-translate-messageformat-compiler#67]
During install it reports: 

`
npm WARN ngx-translate-messageformat-compiler@4.8.0 requires a peer of @angular/core@^6.0.0 || ^7.0.0 || ^8.0.0 || ^9.0.0 || ^10.0.0 but none is installed. You must install peer dependencies yourself. 
`

**Comment by sebastian-zarzycki-es** [comment]
Pretty please.

**Comment by lephyrus** [comment]
I've been meaning to address the new Angular version for weeks, sorry. Version 4.9.0 is published.
