### ISSUE TITLE
Number format

### ISSUE THREAD

**Issue by egalley** [lephyrus/ngx-translate-messageformat-compiler#70]
Hello,

Is there a way to give a number format, a kind of 

...
"display": "{data_value, number, {maximumFractionDigits:2}}"
...

or
...
"display": "{data_value, number, ::.##}"
...

**Comment by lephyrus** [comment]
You can use all syntax supported by Messageformat with this library. The [documentation](http://messageformat.github.io/messageformat/guide/#number) is a bit unclear to me too, but this works for me:

- Message: `"{N} formatted is {N, number, .##}"`
- `[translateParams]="{ N: 2.345 }"`
- Result: `2.345 formatted is 2.35`
