### ISSUE TITLE
Support messageformat v3

### ISSUE THREAD

**Issue by eshkard** [lephyrus/ngx-translate-messageformat-compiler#74]
Hi npm shows warning on "messageformat" package renamed as @messageformat/core.
Will you address this dependency issue?

"warning messageformat@2.3.0: Package renamed as '@messageformat/core', see messageformat.github.io for more details. 'messageformat' will eventually provide a polyfill for Intl.MessageFormat, once it's been defined by Unicode & ECMA."

Thank's,
Evgeny

**Comment by lephyrus** [comment]
It's not just a renamed package - the new version has a number of breaking changes. I have to adapt a few things, shouldn't be hard.

**Comment by lephyrus** [comment]
Turns out the changes in messageformat v3 are anything but trivial for the way we use it, as a compiler at runtime. Don't expect this library to support v3 anytime soon, sorry.

**Comment by tuuling** [comment]
> Turns out the changes in messageformat v3 are anything but trivial for the way we use it, as a compiler at runtime. Don't expect this library to support v3 anytime soon, sorry.

If someone were to provide a PR that supports v3, would you consider making a new major release with messageformat 3 support?
