### ISSUE TITLE
Examples how to use

### ISSUE THREAD

**Issue by web-dave** [lephyrus/ngx-translate-messageformat-compiler#8]
Hi,
Great work dude, I'm fighting with the template, can you provide some examples. 
I tried to get the point from your tests. but with no luck.
short help would be nice.

**Comment by web-dave** [comment]
en.json
```json
{
"icu": "{count, plural, =0{No} one{A} other{#}} {count, plural, one{word} other{words}}"
}
```
Template
```html
<div [translate]="'icu'" [translateParams]="{count: numWords}" ></div>
```

Output:
No words
A word
2 words

**Comment by lephyrus** [comment]
@web-dave I'm glad you've figured it out. The thing is: MessageFormat provides the syntax for your strings and ngx-translate provides the ways of including them in your app. None of it is implemented in this compiler, it's just the "glue". I've still added an example in the hope it will help others. Thanks for the input.

**Comment by Derekjohnson277** [comment]
Can I please get an example an the translations if the count number is dynamic? Meaning that the count number is coming from a variable within the component.

**Comment by web-dave** [comment]
```html
<div>{{ 'words' | translate:{count: numWords} }}</div>
```
Po file 
msgid "words"
msgstr "{count, plural, =0{No} one{A} other{#}} {count, plural, one{Word} other{Words}}"
