### ISSUE TITLE
How to use html tags?

### ISSUE THREAD

**Issue by V1Ray** [lephyrus/ngx-translate-messageformat-compiler#9]
Example JSON:
`{
"INFO": "Welcome to my Angular application!<br><strong>This is an amazing app which uses the latest technologies!</strong>"
}`

**Comment by lephyrus** [comment]
Hi @V1Ray, this is not specific to using the `messageformat-compiler`. Please see here: https://github.com/ngx-translate/core#5-use-html-tags
