### ISSUE TITLE
skeleton support 

### ISSUE THREAD

**Issue by SergejSintschilin** [lephyrus/ngx-translate-messageformat-compiler#94]
Hello. Thank you for the great library.

I found no info inside readme how to add skeleton support for messages.

http://messageformat.github.io/messageformat/api/number-skeleton/

**Comment by lephyrus** [comment]
You can use all syntax supported by Messageformat with this library. The [documentation](http://messageformat.github.io/messageformat/guide/#number) is a bit unclear to me too, but this works for me:

- Message: `"{N} formatted is {N, number, .##}"`
- `[translateParams]="{ N: 2.345 }"`
- Result: `2.345 formatted is 2.35`
